### ISSUE TITLE
Vi går for Azure Notebooks

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/Skolekoden#6]
Vi går "all in" på Azure Notebooks. Skrive om der hvor det er nødvendig, for eksempel her: 
https://github.com/fagstoff/Skolekoden/blob/master/Fagstoff/index.ipynb

**Comment by fuzzbin** [comment]
Enig... Men lima du inn feil lenke? ;-)

**Comment by bitjungle** [comment]
Fiksa lenke

**Comment by bitjungle** [comment]
Ferdig
