### ISSUE TITLE
Euler

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/Skolekoden#7]
Jeg vurderer og forenkle [Euler](https://github.com/fagstoff/Skolekoden/blob/8c85079d3c110f8686769508c5fc926928138da9/Fagstoff/euler.ipynb) ganske kraftig og i sterkere grad fokusere på beregning av neste punkt når vi kjenner stigningstallet og funksjonsverdien til et tidligere punkt. Hva tenker du @bitjungle ?

**Comment by bitjungle** [comment]
Så lenge du forenkler uten å fordumme, er det bare å kjøre på. Husk hva Einstein skal ha sagt: "Everything Should Be Made as Simple as Possible, But Not Simpler".

**Comment by fuzzbin** [comment]
```

# Euler

# Initialbetingelse y(0)=1
# y'=y
dx = 0.5 # Skrittlengde

# Lister for x- og y-verdier
x = [0]
ye = [1]

# Definere Euler

def neste_y():
    return ye[-1] + ye[-1] * dx
```
Er dette å gjøre det for enkelt/fordummende, eller har vi her essensen av Euler?

**Comment by bitjungle** [comment]
Ser vel greit ut. Jeg har tre innspill:

1. Jeg liker å bruke t og dt istedenfor x og dx, for i de fleste eksempler ser vi på noe som endres over tid.

2. Jeg liker å bruke parametre i funksjonskall framfor globale variabler. 

3. Er det noe i det opprinnelige eksemplet vårt som vi bør ta vare på? Ekstrastoff ellerno'?

**Comment by fuzzbin** [comment]
1. Enig!
2. Enig, men i dette tilfellet så symtes jeg litt av poenget forsvinner.
3. Enig.

**Comment by bitjungle** [comment]
2. På hvilken måte?

**Comment by fuzzbin** [comment]
Regner med at du vil sende inn funksjonen som innparameter i Eulerfunksjonen. Da tenker jeg at akkurat i dette tilfellet er funksjonen enklere når man bruker dt (dx) som global variabel, samt henter inn siste verdi fra lista direkte. Grunnen er at utrykket etter return viser det Euler i sin grunnform.

**Comment by bitjungle** [comment]
I eksemplet er vel dt en konstant også, så da skal det vel være DT ;-) 
https://pep8.org/#constants

**Comment by fuzzbin** [comment]
```python
# Euler

# Initialbetingelser
#  y(0)=1
# y'=y
DT = 0.5 # Skrittlengde

# Lister for x- og y-verdier
xe = [0]
ye = [1]

# Definere Euler
def neste_y():
    return ye[-1] + ye[-1] * DT # y_np1 = y_n + y'_n * dt
```
Noe sånt da?

**Comment by fuzzbin** [comment]
Første runde med forenkling er gjennomført. Er fortsatt ikke fornøyd med fagteksten. y=y' er litt forvirrende. Bruke et annet eksempel?

**Comment by fuzzbin** [comment]
Lukker alle issuses i forbindelse med ny struktur på Skolekoden. Vi starter på nytt med blanke ark.
