### ISSUE TITLE
Type-tull

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/Skolekoden#8]
Jeg synes bruken av "type" i [variabler](https://github.com/fagstoff/Python-intro/blob/master/Fagstoff/variabler.ipynb) er helt unødvendig, og gjør ting vanskeligere for nybegynnere. Kan jeg fjerne?

**Comment by fuzzbin** [comment]
Tja, tenker du da å skille på skolekoden og python-intro, eller tenker du for begge. Jeg er på langt vei enig, men tenker også at datatyper er litt viktig. Litt usikker rett og slett..... Under tvil grønt lys fra meg til fjerning. :-)

**Comment by bitjungle** [comment]
Datatyper er kjempeviktig, har absolutt IKKE tenkt å fjerne noe om det. Jeg vil bare fjerne bruken av funksjonen type().

**Comment by fuzzbin** [comment]
Ah, ok. Enig. Den kan sløyfes. :-)

**Comment by fuzzbin** [comment]
Mener du fortsatt at type() skal fjernes? Hvis ja så setter skal jeg prøve å rette opp fagteksten om variabler ASAP.

**Comment by fuzzbin** [comment]
Lukker alle issuses i forbindelse med ny struktur på Skolekoden. Vi starter på nytt med blanke ark.
